spring:
  data:
    mongodb:
      auto-index-creation: true

      uri: mongodb+srv://igorlims:u879k12t07p1@cluster0.5gf88.mongodb.net/adsjobsmanager?retryWrites=true&w=majority

  logging:
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG